### ISSUE TITLE
Login not possible on version 4 ?

### ISSUE THREAD

**Issue by FRigaudie** [alchemy-fr/Phraseanet#2207]
Hi, I installed version 4 on Debain Jessie with PHP 5.6, all green when testing pre-requested.
When I installed I typed a username and a password but it does not work on login.  Then if I try to request password modification I have a CRLF token error displayed on screen.
Any idea why ?

**Comment by maydaylive** [comment]
I have the same issue.... was looking to test version 4
Centos 7 php56 percona 56. nginx.

**Comment by Pascaloub** [comment]
same here,
Freebsd 11.1 jail, php 56 apache 24

**Comment by jmeyerdo** [comment]
Same for me.
But I have errors with last three steps of installation also:

1. bin/console s:i:c
"No handler found for uri [/davdortmund_20171019122222.862927] and method [POST]"

2. bin/console task-manager:task:list
[2017-10-19 13:23:39] phraseanet.ERROR: Unable to notify the task manager with message "information" within timeout of 2 seconds [] []

3. bin/console task-manager:scheduler:run -vvv
[2017-10-19 13:25:00] task-manager logger.DEBUG: Currently running 2 concurrent processes with status started. [] []
Several times...

Maybe login fails due to this?

**Comment by moctardiouf** [comment]
Hi, 
Have you enabled session.cookie_secure  into your php.ini file ?
regards

**Comment by jmeyerdo** [comment]
Yes:
session.cookie_secure = 1

**Comment by moctardiouf** [comment]
session.cookie_secure can only be used if your Phraseanet is over ssl (https)

set  session.cookie_secure = 0 if this is not the case

**Comment by jmeyerdo** [comment]
Great - login seems to be working. Next 500er error. Will go ahead. ;-)

**Comment by nmaillat** [comment]
Hi, 
I close issue, we have updated the warning message in this pr #2321.
Thank
